import { Geist_Mono, Outfit, Instrument_Sans } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  weights: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
const instrument_sans = Instrument_Sans({
  variable: "--font-instrument-sans",
  weights: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${instrument_sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
